// このファイルは自動生成される。直接編集しない。
// 一覧の正典は concepts.md。編集したら npm run gen:concepts を実行する。

import type { Concept, ConceptId } from "./profile";

/** concepts.md で定義された Concept の一覧。定義順は学習の推奨順を兼ねる。 */
export const CONCEPTS: readonly Concept[] = [
  {
    id: "go.variable_declaration",
    label: "変数宣言と :=",
    language: "go",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "go.basic_types",
    label: "基本型とゼロ値",
    language: "go",
    prerequisites: ["go.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "go.control_flow",
    label: "if / for / switch",
    language: "go",
    prerequisites: ["go.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "go.function_basics",
    label: "関数と複数戻り値",
    language: "go",
    prerequisites: ["go.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "go.error_handling",
    label: "error 型と if err != nil",
    language: "go",
    prerequisites: ["go.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "go.slice_basics",
    label: "Slice の生成と参照",
    language: "go",
    prerequisites: ["go.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "go.slice_append",
    label: "append と再割り当て",
    language: "go",
    prerequisites: ["go.slice_basics"],
    source: { kind: "manual" },
  },
  {
    id: "go.map_basics",
    label: "Map と comma-ok",
    language: "go",
    prerequisites: ["go.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "go.struct_basics",
    label: "struct の定義と埋め込み",
    language: "go",
    prerequisites: ["go.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "go.pointer_basics",
    label: "ポインタと & / *",
    language: "go",
    prerequisites: ["go.struct_basics"],
    source: { kind: "manual" },
  },
  {
    id: "go.pointer_receiver",
    label: "値レシーバとポインタレシーバ",
    language: "go",
    prerequisites: ["go.pointer_basics"],
    source: { kind: "manual" },
  },
  {
    id: "go.interface_basics",
    label: "interface の暗黙実装",
    language: "go",
    prerequisites: ["go.struct_basics"],
    source: { kind: "manual" },
  },
  {
    id: "go.goroutine",
    label: "goroutine の起動",
    language: "go",
    prerequisites: ["go.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "go.channel",
    label: "channel の送受信",
    language: "go",
    prerequisites: ["go.goroutine"],
    source: { kind: "manual" },
  },
  {
    id: "go.select",
    label: "select による多重化",
    language: "go",
    prerequisites: ["go.channel"],
    source: { kind: "manual" },
  },
  {
    id: "go.context",
    label: "context によるキャンセル",
    language: "go",
    prerequisites: ["go.channel"],
    source: { kind: "manual" },
  },
  {
    id: "go.defer",
    label: "defer の実行順序",
    language: "go",
    prerequisites: ["go.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "go.package_visibility",
    label: "パッケージと公開/非公開",
    language: "go",
    prerequisites: ["go.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "go.module_dependency",
    label: "go.mod と依存管理",
    language: "go",
    prerequisites: ["go.package_visibility"],
    source: { kind: "manual" },
  },
  {
    id: "go.testing_basics",
    label: "testing パッケージ",
    language: "go",
    prerequisites: ["go.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.variable_declaration",
    label: "変数宣言と const / let",
    language: "ts",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "ts.primitive_types",
    label: "プリミティブ型と値",
    language: "ts",
    prerequisites: ["ts.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "ts.control_flow",
    label: "if / switch / ループ",
    language: "ts",
    prerequisites: ["ts.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "ts.function_basics",
    label: "関数宣言と引数・戻り値",
    language: "ts",
    prerequisites: ["ts.primitive_types"],
    source: { kind: "manual" },
  },
  {
    id: "ts.object_basics",
    label: "オブジェクトとプロパティ",
    language: "ts",
    prerequisites: ["ts.primitive_types"],
    source: { kind: "manual" },
  },
  {
    id: "ts.array_basics",
    label: "配列の生成と要素アクセス",
    language: "ts",
    prerequisites: ["ts.primitive_types"],
    source: { kind: "manual" },
  },
  {
    id: "ts.array_methods",
    label: "map / filter / reduce",
    language: "ts",
    prerequisites: ["ts.array_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.closure",
    label: "クロージャとレキシカルスコープ",
    language: "ts",
    prerequisites: ["ts.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.class_basics",
    label: "class とインスタンス",
    language: "ts",
    prerequisites: ["ts.object_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.module_basics",
    label: "import / export とモジュール",
    language: "ts",
    prerequisites: ["ts.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.error_handling",
    label: "throw / try / catch",
    language: "ts",
    prerequisites: ["ts.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.promise_basics",
    label: "Promise と状態遷移",
    language: "ts",
    prerequisites: ["ts.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.async_await",
    label: "async / await",
    language: "ts",
    prerequisites: ["ts.promise_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.type_annotation",
    label: "型注釈と型推論",
    language: "ts",
    prerequisites: ["ts.primitive_types"],
    source: { kind: "manual" },
  },
  {
    id: "ts.interface_basics",
    label: "interface とオブジェクト型",
    language: "ts",
    prerequisites: ["ts.type_annotation"],
    source: { kind: "manual" },
  },
  {
    id: "ts.union_type",
    label: "union 型とリテラル型",
    language: "ts",
    prerequisites: ["ts.type_annotation"],
    source: { kind: "manual" },
  },
  {
    id: "ts.type_narrowing",
    label: "型ガードと絞り込み",
    language: "ts",
    prerequisites: ["ts.union_type"],
    source: { kind: "manual" },
  },
  {
    id: "ts.generic",
    label: "ジェネリクスと型パラメータ",
    language: "ts",
    prerequisites: ["ts.interface_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.utility_type",
    label: "Partial / Pick などのユーティリティ型",
    language: "ts",
    prerequisites: ["ts.generic"],
    source: { kind: "manual" },
  },
  {
    id: "ts.testing_basics",
    label: "テストの構成とアサーション",
    language: "ts",
    prerequisites: ["ts.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "python.variable_declaration",
    label: "変数と代入",
    language: "python",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "python.basic_types",
    label: "数値・文字列・真偽値と None",
    language: "python",
    prerequisites: ["python.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "python.control_flow",
    label: "if / for / while",
    language: "python",
    prerequisites: ["python.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "python.function_basics",
    label: "def と引数・戻り値",
    language: "python",
    prerequisites: ["python.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "python.list_basics",
    label: "list とスライス",
    language: "python",
    prerequisites: ["python.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "python.dict_basics",
    label: "dict と get / in",
    language: "python",
    prerequisites: ["python.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "python.tuple_set",
    label: "tuple と set",
    language: "python",
    prerequisites: ["python.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "python.comprehension",
    label: "内包表記",
    language: "python",
    prerequisites: ["python.list_basics"],
    source: { kind: "manual" },
  },
  {
    id: "python.class_basics",
    label: "class とインスタンス",
    language: "python",
    prerequisites: ["python.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "python.error_handling",
    label: "raise / try / except",
    language: "python",
    prerequisites: ["python.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "python.module_basics",
    label: "import とモジュール",
    language: "python",
    prerequisites: ["python.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "python.typing",
    label: "型ヒント",
    language: "python",
    prerequisites: ["python.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "python.venv_dependency",
    label: "venv と pip による依存管理",
    language: "python",
    prerequisites: ["python.module_basics"],
    source: { kind: "manual" },
  },
  {
    id: "python.testing_basics",
    label: "pytest の基本",
    language: "python",
    prerequisites: ["python.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "rust.variable_declaration",
    label: "let と mut",
    language: "rust",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "rust.basic_types",
    label: "スカラ型と複合型",
    language: "rust",
    prerequisites: ["rust.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "rust.control_flow",
    label: "if / loop / match",
    language: "rust",
    prerequisites: ["rust.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "rust.function_basics",
    label: "fn と戻り値",
    language: "rust",
    prerequisites: ["rust.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "rust.ownership",
    label: "所有権と move",
    language: "rust",
    prerequisites: ["rust.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "rust.borrowing",
    label: "参照と借用",
    language: "rust",
    prerequisites: ["rust.ownership"],
    source: { kind: "manual" },
  },
  {
    id: "rust.lifetime",
    label: "ライフタイム注釈",
    language: "rust",
    prerequisites: ["rust.borrowing"],
    source: { kind: "manual" },
  },
  {
    id: "rust.struct_basics",
    label: "struct と impl",
    language: "rust",
    prerequisites: ["rust.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "rust.enum_match",
    label: "enum と match",
    language: "rust",
    prerequisites: ["rust.struct_basics"],
    source: { kind: "manual" },
  },
  {
    id: "rust.error_handling",
    label: "Result / Option と ?",
    language: "rust",
    prerequisites: ["rust.enum_match"],
    source: { kind: "manual" },
  },
  {
    id: "rust.trait_basics",
    label: "trait と実装",
    language: "rust",
    prerequisites: ["rust.struct_basics"],
    source: { kind: "manual" },
  },
  {
    id: "rust.cargo_dependency",
    label: "Cargo とクレート",
    language: "rust",
    prerequisites: ["rust.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "rust.testing_basics",
    label: "#[test] と cargo test",
    language: "rust",
    prerequisites: ["rust.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "java.variable_declaration",
    label: "変数宣言と基本型",
    language: "java",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "java.control_flow",
    label: "if / for / switch",
    language: "java",
    prerequisites: ["java.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "java.class_basics",
    label: "class とインスタンス",
    language: "java",
    prerequisites: ["java.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "java.method_basics",
    label: "メソッドとオーバーロード",
    language: "java",
    prerequisites: ["java.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "java.inheritance",
    label: "継承と override",
    language: "java",
    prerequisites: ["java.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "java.interface_basics",
    label: "interface と実装",
    language: "java",
    prerequisites: ["java.inheritance"],
    source: { kind: "manual" },
  },
  {
    id: "java.collection_basics",
    label: "List / Map / Set",
    language: "java",
    prerequisites: ["java.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "java.generics",
    label: "ジェネリクス",
    language: "java",
    prerequisites: ["java.collection_basics"],
    source: { kind: "manual" },
  },
  {
    id: "java.stream_api",
    label: "Stream API とラムダ",
    language: "java",
    prerequisites: ["java.generics"],
    source: { kind: "manual" },
  },
  {
    id: "java.error_handling",
    label: "throw / try / catch",
    language: "java",
    prerequisites: ["java.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "java.package_build",
    label: "package とビルドツール",
    language: "java",
    prerequisites: ["java.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "java.testing_basics",
    label: "JUnit の基本",
    language: "java",
    prerequisites: ["java.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.variable_declaration",
    label: "var と型宣言",
    language: "csharp",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "csharp.basic_types",
    label: "値型と参照型",
    language: "csharp",
    prerequisites: ["csharp.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.control_flow",
    label: "if / for / switch",
    language: "csharp",
    prerequisites: ["csharp.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.class_basics",
    label: "class とプロパティ",
    language: "csharp",
    prerequisites: ["csharp.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.method_basics",
    label: "メソッドと引数",
    language: "csharp",
    prerequisites: ["csharp.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.inheritance",
    label: "継承と override",
    language: "csharp",
    prerequisites: ["csharp.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.interface_basics",
    label: "interface と実装",
    language: "csharp",
    prerequisites: ["csharp.inheritance"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.collection_basics",
    label: "List / Dictionary",
    language: "csharp",
    prerequisites: ["csharp.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.linq",
    label: "LINQ とラムダ",
    language: "csharp",
    prerequisites: ["csharp.collection_basics"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.async_await",
    label: "async / await と Task",
    language: "csharp",
    prerequisites: ["csharp.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.error_handling",
    label: "throw / try / catch",
    language: "csharp",
    prerequisites: ["csharp.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.dotnet_project",
    label: "csproj と dotnet CLI",
    language: "csharp",
    prerequisites: ["csharp.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.testing_basics",
    label: "xUnit の基本",
    language: "csharp",
    prerequisites: ["csharp.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "php.variable_declaration",
    label: "$変数と代入",
    language: "php",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "php.basic_types",
    label: "スカラ型と null",
    language: "php",
    prerequisites: ["php.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "php.control_flow",
    label: "if / foreach / while",
    language: "php",
    prerequisites: ["php.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "php.function_basics",
    label: "function と引数・戻り値",
    language: "php",
    prerequisites: ["php.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "php.array_basics",
    label: "array と連想配列",
    language: "php",
    prerequisites: ["php.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "php.string_basics",
    label: "文字列操作とヒアドキュメント",
    language: "php",
    prerequisites: ["php.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "php.class_basics",
    label: "class とインスタンス",
    language: "php",
    prerequisites: ["php.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "php.error_handling",
    label: "throw / try / catch",
    language: "php",
    prerequisites: ["php.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "php.web_request",
    label: "$_GET / $_POST とレスポンス",
    language: "php",
    prerequisites: ["php.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "php.composer",
    label: "Composer と autoload",
    language: "php",
    prerequisites: ["php.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "php.testing_basics",
    label: "PHPUnit の基本",
    language: "php",
    prerequisites: ["php.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.variable_declaration",
    label: "変数と代入",
    language: "ruby",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "ruby.basic_types",
    label: "数値・文字列・シンボルと nil",
    language: "ruby",
    prerequisites: ["ruby.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.control_flow",
    label: "if / each / while",
    language: "ruby",
    prerequisites: ["ruby.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.method_basics",
    label: "def と引数・戻り値",
    language: "ruby",
    prerequisites: ["ruby.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.block_basics",
    label: "ブロックと each / map",
    language: "ruby",
    prerequisites: ["ruby.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.array_hash",
    label: "Array と Hash",
    language: "ruby",
    prerequisites: ["ruby.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.class_basics",
    label: "class とインスタンス変数",
    language: "ruby",
    prerequisites: ["ruby.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.module_mixin",
    label: "module と mixin",
    language: "ruby",
    prerequisites: ["ruby.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.error_handling",
    label: "raise / rescue / ensure",
    language: "ruby",
    prerequisites: ["ruby.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.gem_bundler",
    label: "gem と Bundler",
    language: "ruby",
    prerequisites: ["ruby.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.testing_basics",
    label: "Minitest / RSpec の基本",
    language: "ruby",
    prerequisites: ["ruby.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "git.repository",
    label: "init / clone とリポジトリ",
    language: "git",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "git.staging",
    label: "add とステージング",
    language: "git",
    prerequisites: ["git.repository"],
    source: { kind: "manual" },
  },
  {
    id: "git.commit",
    label: "コミットとメッセージ",
    language: "git",
    prerequisites: ["git.staging"],
    source: { kind: "manual" },
  },
  {
    id: "git.log_history",
    label: "log / diff で履歴を読む",
    language: "git",
    prerequisites: ["git.commit"],
    source: { kind: "manual" },
  },
  {
    id: "git.branch",
    label: "ブランチと切り替え",
    language: "git",
    prerequisites: ["git.commit"],
    source: { kind: "manual" },
  },
  {
    id: "git.merge",
    label: "マージとコンフリクト解消",
    language: "git",
    prerequisites: ["git.branch"],
    source: { kind: "manual" },
  },
  {
    id: "git.rebase",
    label: "rebase と履歴の書き換え",
    language: "git",
    prerequisites: ["git.merge"],
    source: { kind: "manual" },
  },
  {
    id: "git.remote",
    label: "remote / push / pull",
    language: "git",
    prerequisites: ["git.commit"],
    source: { kind: "manual" },
  },
  {
    id: "git.stash",
    label: "stash と一時退避",
    language: "git",
    prerequisites: ["git.commit"],
    source: { kind: "manual" },
  },
  {
    id: "git.undo",
    label: "reset / revert による取り消し",
    language: "git",
    prerequisites: ["git.commit"],
    source: { kind: "manual" },
  },
  {
    id: "design.naming",
    label: "命名と意図の表現",
    language: "design",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "design.function_size",
    label: "関数の分割と責務",
    language: "design",
    prerequisites: ["design.naming"],
    source: { kind: "manual" },
  },
  {
    id: "design.dry",
    label: "重複と抽象化",
    language: "design",
    prerequisites: ["design.function_size"],
    source: { kind: "manual" },
  },
  {
    id: "design.dependency",
    label: "依存の方向と結合度",
    language: "design",
    prerequisites: ["design.function_size"],
    source: { kind: "manual" },
  },
  {
    id: "design.interface_contract",
    label: "インターフェースと契約",
    language: "design",
    prerequisites: ["design.dependency"],
    source: { kind: "manual" },
  },
  {
    id: "design.error_design",
    label: "エラーの表現と伝播",
    language: "design",
    prerequisites: ["design.function_size"],
    source: { kind: "manual" },
  },
  {
    id: "design.state",
    label: "状態と副作用の管理",
    language: "design",
    prerequisites: ["design.function_size"],
    source: { kind: "manual" },
  },
  {
    id: "design.testability",
    label: "テストしやすい設計",
    language: "design",
    prerequisites: ["design.dependency"],
    source: { kind: "manual" },
  },
  {
    id: "db.relational_model",
    label: "テーブルとリレーション",
    language: "db",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "db.sql_select",
    label: "SELECT と WHERE",
    language: "db",
    prerequisites: ["db.relational_model"],
    source: { kind: "manual" },
  },
  {
    id: "db.sql_join",
    label: "JOIN と結合",
    language: "db",
    prerequisites: ["db.sql_select"],
    source: { kind: "manual" },
  },
  {
    id: "db.sql_aggregate",
    label: "GROUP BY と集約",
    language: "db",
    prerequisites: ["db.sql_select"],
    source: { kind: "manual" },
  },
  {
    id: "db.sql_write",
    label: "INSERT / UPDATE / DELETE",
    language: "db",
    prerequisites: ["db.relational_model"],
    source: { kind: "manual" },
  },
  {
    id: "db.normalization",
    label: "正規化と冗長性",
    language: "db",
    prerequisites: ["db.relational_model"],
    source: { kind: "manual" },
  },
  {
    id: "db.index",
    label: "インデックスと検索性能",
    language: "db",
    prerequisites: ["db.sql_select"],
    source: { kind: "manual" },
  },
  {
    id: "db.transaction",
    label: "トランザクションと整合性",
    language: "db",
    prerequisites: ["db.sql_write"],
    source: { kind: "manual" },
  },
  {
    id: "db.migration",
    label: "スキーマ変更とマイグレーション",
    language: "db",
    prerequisites: ["db.relational_model"],
    source: { kind: "manual" },
  },
  {
    id: "http.request_response",
    label: "リクエストとレスポンスの構造",
    language: "http",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "http.method_semantics",
    label: "GET / POST などメソッドの意味",
    language: "http",
    prerequisites: ["http.request_response"],
    source: { kind: "manual" },
  },
  {
    id: "http.status_code",
    label: "ステータスコードの区分",
    language: "http",
    prerequisites: ["http.request_response"],
    source: { kind: "manual" },
  },
  {
    id: "http.header",
    label: "ヘッダと Content-Type",
    language: "http",
    prerequisites: ["http.request_response"],
    source: { kind: "manual" },
  },
  {
    id: "http.rest",
    label: "REST のリソース指向",
    language: "http",
    prerequisites: ["http.method_semantics"],
    source: { kind: "manual" },
  },
  {
    id: "http.cors",
    label: "CORS とオリジン",
    language: "http",
    prerequisites: ["http.header"],
    source: { kind: "manual" },
  },
  {
    id: "http.auth",
    label: "認証ヘッダとトークン",
    language: "http",
    prerequisites: ["http.header"],
    source: { kind: "manual" },
  },
];

/** Concept ID から定義を引く。未知の ID では undefined を返す。 */
export const CONCEPT_BY_ID: ReadonlyMap<ConceptId, Concept> = new Map(
  CONCEPTS.map((concept) => [concept.id, concept]),
);
