// このファイルは自動生成される。直接編集しない。
// 一覧の正典は concepts.md。編集したら npm run gen:concepts を実行する。

import type { Concept, ConceptId } from "./profile";

/** concepts.md で定義された Concept の一覧。定義順は学習の推奨順を兼ねる。 */
export const CONCEPTS: readonly Concept[] = [
  {
    id: "go.variable_declaration",
    label: "変数宣言と :=",
    language: "go",
    summary: "var と := の使い分け。:= は関数の内側でしか書けず、型は右辺から推論される。",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "go.basic_types",
    label: "基本型とゼロ値",
    language: "go",
    summary: "int / string / bool などの基本型。宣言しただけで 0、空文字列、false が入るため、未初期化の状態が存在しない。",
    prerequisites: ["go.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "go.control_flow",
    label: "if / for / switch",
    language: "go",
    summary: "条件分岐と繰り返し。ループは for だけで while は無く、switch は各 case の末尾で自動的に抜ける。",
    prerequisites: ["go.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "go.function_basics",
    label: "関数と複数戻り値",
    language: "go",
    summary: "func による定義。戻り値を複数返せるため、結果とエラーを同時に返す形が標準になっている。",
    prerequisites: ["go.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "go.error_handling",
    label: "error 型と if err != nil",
    language: "go",
    summary: "エラーは例外ではなく戻り値である。呼び出しごとに err を確認し、fmt.Errorf の %w で包んで文脈を足す。",
    prerequisites: ["go.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "go.slice_basics",
    label: "Slice の生成と参照",
    language: "go",
    summary: "可変長の列。内部は配列への参照（先頭・長さ・容量）なので、コピーしても同じ配列を指す。",
    prerequisites: ["go.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "go.slice_append",
    label: "append と再割り当て",
    language: "go",
    summary: "append は容量が足りないと新しい配列へ移すため、戻り値を必ず受け取り直す。元の変数だけを見ていると変更が消える。",
    prerequisites: ["go.slice_basics"],
    source: { kind: "manual" },
  },
  {
    id: "go.map_basics",
    label: "Map と comma-ok",
    language: "go",
    summary: "キーと値の対応表。v, ok := m[k] の ok で、値がゼロ値なのかキーが無いのかを区別する。",
    prerequisites: ["go.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "go.struct_basics",
    label: "struct の定義と埋め込み",
    language: "go",
    summary: "フィールドの集まりで型を作る。埋め込むと、その型のフィールドとメソッドをそのまま自分のものとして呼べる。",
    prerequisites: ["go.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "go.pointer_basics",
    label: "ポインタと & / *",
    language: "go",
    summary: "& でアドレスを取り、* で指し先を読み書きする。値のコピーを避け、呼び出し先から元の値を変えるために使う。",
    prerequisites: ["go.struct_basics"],
    source: { kind: "manual" },
  },
  {
    id: "go.pointer_receiver",
    label: "値レシーバとポインタレシーバ",
    language: "go",
    summary: "値レシーバのメソッドには複製が渡るので、中で変えても呼び出し元へ伝わらない。状態を変えるならポインタレシーバにする。",
    prerequisites: ["go.pointer_basics"],
    source: { kind: "manual" },
  },
  {
    id: "go.interface_basics",
    label: "interface の暗黙実装",
    language: "go",
    summary: "メソッドの集合を満たす型は、宣言なしにその interface を実装したことになる。実装側は interface を知らなくてよい。",
    prerequisites: ["go.struct_basics"],
    source: { kind: "manual" },
  },
  {
    id: "go.goroutine",
    label: "goroutine の起動",
    language: "go",
    summary: "go で関数を並行に走らせる。呼び出しは即座に返るため、終了を待つ仕組みが無ければ main の終了で打ち切られる。",
    prerequisites: ["go.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "go.channel",
    label: "channel の送受信",
    language: "go",
    summary: "goroutine 間で値を受け渡す通路。受信は値が来るまで待ち、バッファが無ければ送信側も受け取られるまで待つ。",
    prerequisites: ["go.goroutine"],
    source: { kind: "manual" },
  },
  {
    id: "go.select",
    label: "select による多重化",
    language: "go",
    summary: "複数の channel を同時に待ち、準備できたものから処理する。default を書くと待たずに次へ進める。",
    prerequisites: ["go.channel"],
    source: { kind: "manual" },
  },
  {
    id: "go.context",
    label: "context によるキャンセル",
    language: "go",
    summary: "打ち切りと締め切りを呼び出しの連鎖へ伝える仕組み。Done を監視して途中で止め、cancel は defer で必ず呼ぶ。",
    prerequisites: ["go.channel"],
    source: { kind: "manual" },
  },
  {
    id: "go.defer",
    label: "defer の実行順序",
    language: "go",
    summary: "関数を抜ける直前の実行を予約する。登録の逆順に走るので、後片付けを取得処理の隣に書ける。",
    prerequisites: ["go.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "go.package_visibility",
    label: "パッケージと公開/非公開",
    language: "go",
    summary: "識別子の先頭が大文字なら他パッケージから見え、小文字ならパッケージ内に閉じる。アクセス修飾子は無い。",
    prerequisites: ["go.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "go.module_dependency",
    label: "go.mod と依存管理",
    language: "go",
    summary: "モジュール名と依存バージョンを go.mod に記録する。go get で足し、go mod tidy で使っていない依存を落とす。",
    prerequisites: ["go.package_visibility"],
    source: { kind: "manual" },
  },
  {
    id: "go.testing_basics",
    label: "testing パッケージ",
    language: "go",
    summary: "_test.go に TestXxx(t *testing.T) を書き、go test で走らせる。失敗は t.Errorf で報告し、戻り値では返さない。",
    prerequisites: ["go.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.variable_declaration",
    label: "変数宣言と const / let",
    language: "ts",
    summary: "const は再代入を禁じ、let は許す。const でもオブジェクトの中身は変えられる。var はブロックスコープを持たないため使わない。",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "ts.primitive_types",
    label: "プリミティブ型と値",
    language: "ts",
    summary: "string / number / boolean と、値が無いことを表す null と undefined。number は整数と小数を区別しない。",
    prerequisites: ["ts.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "ts.control_flow",
    label: "if / switch / ループ",
    language: "ts",
    summary: "条件分岐と繰り返し。条件は真偽値へ暗黙変換されるため、空文字列や 0 が偽として扱われる。",
    prerequisites: ["ts.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "ts.function_basics",
    label: "関数宣言と引数・戻り値",
    language: "ts",
    summary: "function とアロー関数。引数と戻り値に型を付けられ、既定値や可変長引数も書ける。this の扱いは両者で違う。",
    prerequisites: ["ts.primitive_types"],
    source: { kind: "manual" },
  },
  {
    id: "ts.object_basics",
    label: "オブジェクトとプロパティ",
    language: "ts",
    summary: "キーと値の集まり。ドットや角括弧で参照し、分割代入とスプレッドで取り出しや組み替えを行う。",
    prerequisites: ["ts.primitive_types"],
    source: { kind: "manual" },
  },
  {
    id: "ts.array_basics",
    label: "配列の生成と要素アクセス",
    language: "ts",
    summary: "値を並べた可変長の列。添字は 0 から始まり、範囲外を読むと例外ではなく undefined が返る。",
    prerequisites: ["ts.primitive_types"],
    source: { kind: "manual" },
  },
  {
    id: "ts.array_methods",
    label: "map / filter / reduce",
    language: "ts",
    summary: "配列を変換・絞り込み・集約する高階関数。元の配列を書き換えず、新しい配列や値を返す。",
    prerequisites: ["ts.array_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.closure",
    label: "クロージャとレキシカルスコープ",
    language: "ts",
    summary: "関数が定義された場所の変数を覚えて持ち歩く仕組み。状態を閉じ込められる反面、捕まえた変数を後から変えると全員が新しい値を見る。",
    prerequisites: ["ts.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.class_basics",
    label: "class とインスタンス",
    language: "ts",
    summary: "class でひな形を定義し、new で実体を作る。constructor で初期化し、フィールド・メソッド・継承を持つ。",
    prerequisites: ["ts.object_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.module_basics",
    label: "import / export とモジュール",
    language: "ts",
    summary: "ファイル単位で公開するものを export し、使う側が import する。export していない値は外から触れない。",
    prerequisites: ["ts.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.error_handling",
    label: "throw / try / catch",
    language: "ts",
    summary: "例外を投げて捕まえる。catch が受け取る値は unknown なので、型を確かめてから扱う。finally は成功でも失敗でも走る。",
    prerequisites: ["ts.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.promise_basics",
    label: "Promise と状態遷移",
    language: "ts",
    summary: "非同期処理の結果を表す値。pending から fulfilled か rejected へ一度だけ移り、then / catch で続きを繋ぐ。",
    prerequisites: ["ts.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.async_await",
    label: "async / await",
    language: "ts",
    summary: "Promise を同期的な見た目で書く構文。await で解決を待ち、失敗は try / catch で受ける。async 関数は必ず Promise を返す。",
    prerequisites: ["ts.promise_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.type_annotation",
    label: "型注釈と型推論",
    language: "ts",
    summary: "変数や関数へ型を宣言する。多くの場所は推論で足りるので、引数・戻り値・公開する境界に付けるのが基本になる。",
    prerequisites: ["ts.primitive_types"],
    source: { kind: "manual" },
  },
  {
    id: "ts.interface_basics",
    label: "interface とオブジェクト型",
    language: "ts",
    summary: "オブジェクトの形に名前を付ける。名前ではなく構造が一致すれば同じ型として通る。",
    prerequisites: ["ts.type_annotation"],
    source: { kind: "manual" },
  },
  {
    id: "ts.union_type",
    label: "union 型とリテラル型",
    language: "ts",
    summary: "複数の型のどれか一方を取ることを表す型。文字列リテラルを並べると、取りうる値そのものを型で固定できる。",
    prerequisites: ["ts.type_annotation"],
    source: { kind: "manual" },
  },
  {
    id: "ts.type_narrowing",
    label: "型ガードと絞り込み",
    language: "ts",
    summary: "typeof や in、null の判定で union を1つの型へ絞る。絞り込めた範囲でだけ、その型のプロパティを触れる。",
    prerequisites: ["ts.union_type"],
    source: { kind: "manual" },
  },
  {
    id: "ts.generic",
    label: "ジェネリクスと型パラメータ",
    language: "ts",
    summary: "型を引数として受け取り、中身の型を保ったまま使い回せる関数や型を書く。any で潰さずに汎用化する手段である。",
    prerequisites: ["ts.interface_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ts.utility_type",
    label: "Partial / Pick などのユーティリティ型",
    language: "ts",
    summary: "既存の型から別の型を導く組み込みの型。Partial で省略可能にし、Pick や Omit でプロパティを取捨する。",
    prerequisites: ["ts.generic"],
    source: { kind: "manual" },
  },
  {
    id: "ts.testing_basics",
    label: "テストの構成とアサーション",
    language: "ts",
    summary: "describe / test で単位を分け、期待値との一致を検証する。失敗したときに原因が特定できる粒度に分ける。",
    prerequisites: ["ts.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "python.variable_declaration",
    label: "変数と代入",
    language: "python",
    summary: "宣言は無く、代入した時点で名前が値を指す。型は値が持つので、同じ名前へ別の型を入れられる。",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "python.basic_types",
    label: "数値・文字列・真偽値と None",
    language: "python",
    summary: "int / float / str / bool と、値が無いことを表す None。str は変更できず、操作は新しい文字列を返す。",
    prerequisites: ["python.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "python.control_flow",
    label: "if / for / while",
    language: "python",
    summary: "条件分岐と繰り返し。ブロックはインデントで表し、for は反復可能オブジェクトから要素を1つずつ受け取る。",
    prerequisites: ["python.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "python.function_basics",
    label: "def と引数・戻り値",
    language: "python",
    summary: "def で定義する。既定値・キーワード引数・可変長引数を取れ、return が無ければ None を返す。",
    prerequisites: ["python.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "python.list_basics",
    label: "list とスライス",
    language: "python",
    summary: "順序を持つ可変長の列。負の添字で末尾から数え、[start:end] で部分列を新しい list として取り出す。",
    prerequisites: ["python.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "python.dict_basics",
    label: "dict と get / in",
    language: "python",
    summary: "キーと値の対応表。無いキーを添字で読むと例外になるため、get で既定値を返すか in で存在を確かめる。",
    prerequisites: ["python.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "python.tuple_set",
    label: "tuple と set",
    language: "python",
    summary: "tuple は変更できない並び、set は重複の無い集合で順序を持たない。何を保証したいかで list と使い分ける。",
    prerequisites: ["python.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "python.comprehension",
    label: "内包表記",
    language: "python",
    summary: "繰り返しと条件を1つの式で書き、list / dict / set を作る記法。append を並べる手続きを短く表せる。",
    prerequisites: ["python.list_basics"],
    source: { kind: "manual" },
  },
  {
    id: "python.class_basics",
    label: "class とインスタンス",
    language: "python",
    summary: "class でひな形を定義し、__init__ で初期化する。メソッドの第1引数 self がインスタンス自身を指す。",
    prerequisites: ["python.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "python.error_handling",
    label: "raise / try / except",
    language: "python",
    summary: "例外を投げて捕まえる。except は種類を指定して受け、else と finally で後処理を分ける。",
    prerequisites: ["python.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "python.module_basics",
    label: "import とモジュール",
    language: "python",
    summary: "ファイルとディレクトリがモジュールとパッケージになる。import で名前空間へ取り込み、__name__ で直接実行かを判定する。",
    prerequisites: ["python.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "python.typing",
    label: "型ヒント",
    language: "python",
    summary: "引数や戻り値に型を注釈する。実行時には強制されないが、静的解析とエディタの補完が効くようになる。",
    prerequisites: ["python.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "python.venv_dependency",
    label: "venv と pip による依存管理",
    language: "python",
    summary: "プロジェクトごとに仮想環境を作り、pip で依存を入れる。環境を分けないと別のプロジェクトとバージョンが衝突する。",
    prerequisites: ["python.module_basics"],
    source: { kind: "manual" },
  },
  {
    id: "python.testing_basics",
    label: "pytest の基本",
    language: "python",
    summary: "test_ で始まる関数を書き、assert で期待値を確かめる。前準備は fixture にまとめて共有する。",
    prerequisites: ["python.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "rust.variable_declaration",
    label: "let と mut",
    language: "rust",
    summary: "let の束縛は既定で不変で、書き換えるには mut を付ける。同じ名前を let で再束縛すると別の値になる。",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "rust.basic_types",
    label: "スカラ型と複合型",
    language: "rust",
    summary: "整数・浮動小数・bool・char と、tuple や配列。整数の桁あふれはデバッグビルドで panic する。",
    prerequisites: ["rust.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "rust.control_flow",
    label: "if / loop / match",
    language: "rust",
    summary: "if も match も値を返す式である。繰り返しは loop / while / for で、loop は break に値を持たせられる。",
    prerequisites: ["rust.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "rust.function_basics",
    label: "fn と戻り値",
    language: "rust",
    summary: "fn で定義し、引数と戻り値の型は必ず書く。最後の式が戻り値になり、セミコロンを付けると値が返らない。",
    prerequisites: ["rust.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "rust.ownership",
    label: "所有権と move",
    language: "rust",
    summary: "値の所有者は常に1つで、代入や引数渡しで移動する。所有者がスコープを抜けた時点で値は破棄される。",
    prerequisites: ["rust.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "rust.borrowing",
    label: "参照と借用",
    language: "rust",
    summary: "& で所有権を移さずに貸す。不変の借用は同時に何個でも、可変の借用は同時に1つだけ許される。",
    prerequisites: ["rust.ownership"],
    source: { kind: "manual" },
  },
  {
    id: "rust.lifetime",
    label: "ライフタイム注釈",
    language: "rust",
    summary: "参照が有効な範囲をコンパイラへ伝える注釈。返す参照がどの引数由来かを示し、破棄済みの値への参照を防ぐ。",
    prerequisites: ["rust.borrowing"],
    source: { kind: "manual" },
  },
  {
    id: "rust.struct_basics",
    label: "struct と impl",
    language: "rust",
    summary: "フィールドの集まりを struct で定義し、メソッドは impl に書く。self を借用するか消費するかでできることが変わる。",
    prerequisites: ["rust.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "rust.enum_match",
    label: "enum と match",
    language: "rust",
    summary: "取りうる状態を列挙し、match で分岐する。すべての場合を書かないとコンパイルが通らない。",
    prerequisites: ["rust.struct_basics"],
    source: { kind: "manual" },
  },
  {
    id: "rust.error_handling",
    label: "Result / Option と ?",
    language: "rust",
    summary: "失敗は Result、値の不在は Option で型に表す。? で呼び出し元へ早く返し、unwrap は失敗すると panic する。",
    prerequisites: ["rust.enum_match"],
    source: { kind: "manual" },
  },
  {
    id: "rust.trait_basics",
    label: "trait と実装",
    language: "rust",
    summary: "共通のふるまいを trait で定義し、型ごとに impl する。ジェネリクスの境界としても使う。",
    prerequisites: ["rust.struct_basics"],
    source: { kind: "manual" },
  },
  {
    id: "rust.cargo_dependency",
    label: "Cargo とクレート",
    language: "rust",
    summary: "Cargo.toml に依存を書き、cargo build や cargo test で解決する。Cargo.lock でバージョンを固定する。",
    prerequisites: ["rust.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "rust.testing_basics",
    label: "#[test] と cargo test",
    language: "rust",
    summary: "#[test] を付けた関数を cargo test で走らせる。assert_eq! で期待値を確かめ、#[cfg(test)] のモジュールへ置く。",
    prerequisites: ["rust.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "java.variable_declaration",
    label: "変数宣言と基本型",
    language: "java",
    summary: "型を明記して宣言する。int や double の基本型は値そのものを持ち、String やクラスは参照を持つ。",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "java.control_flow",
    label: "if / for / switch",
    language: "java",
    summary: "条件分岐と繰り返し。拡張 for でコレクションを辿り、switch は break を書かないと次の case へ落ちる。",
    prerequisites: ["java.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "java.class_basics",
    label: "class とインスタンス",
    language: "java",
    summary: "class でフィールドとメソッドを定義し、new で実体を作る。コンストラクタで初期状態を決める。",
    prerequisites: ["java.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "java.method_basics",
    label: "メソッドとオーバーロード",
    language: "java",
    summary: "戻り値の型と引数を宣言して定義する。同じ名前でも引数の型や個数が違えば別のメソッドとして持てる。",
    prerequisites: ["java.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "java.inheritance",
    label: "継承と override",
    language: "java",
    summary: "extends で親の実装を引き継ぎ、@Override でふるまいを差し替える。super で親の実装を呼べる。",
    prerequisites: ["java.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "java.interface_basics",
    label: "interface と実装",
    language: "java",
    summary: "実装を持たないメソッドの約束を定義し、implements で満たす。1つのクラスが複数を実装できる。",
    prerequisites: ["java.inheritance"],
    source: { kind: "manual" },
  },
  {
    id: "java.collection_basics",
    label: "List / Map / Set",
    language: "java",
    summary: "順序つきの List、キーと値の Map、重複の無い Set。変数の型は実装クラスではなく interface で受ける。",
    prerequisites: ["java.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "java.generics",
    label: "ジェネリクス",
    language: "java",
    summary: "型パラメータで中身の型を固定し、キャストなしに型安全なコレクションや API を書く。",
    prerequisites: ["java.collection_basics"],
    source: { kind: "manual" },
  },
  {
    id: "java.stream_api",
    label: "Stream API とラムダ",
    language: "java",
    summary: "コレクションを filter / map / collect の流れで処理する。ラムダ式で処理を渡し、元のコレクションは変えない。",
    prerequisites: ["java.generics"],
    source: { kind: "manual" },
  },
  {
    id: "java.error_handling",
    label: "throw / try / catch",
    language: "java",
    summary: "例外を投げて捕まえる。検査例外は throws の宣言か catch が必須で、try-with-resources は後片付けを任せられる。",
    prerequisites: ["java.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "java.package_build",
    label: "package とビルドツール",
    language: "java",
    summary: "package でクラスを名前空間へ置き、ディレクトリ構成と対応させる。依存とビルドは Maven や Gradle が管理する。",
    prerequisites: ["java.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "java.testing_basics",
    label: "JUnit の基本",
    language: "java",
    summary: "@Test を付けたメソッドを走らせ、assertEquals などで期待値を確かめる。前準備は @BeforeEach に置く。",
    prerequisites: ["java.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.variable_declaration",
    label: "var と型宣言",
    language: "csharp",
    summary: "型を明記するか var で推論させる。var でも型は宣言時に確定し、後から別の型は入らない。",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "csharp.basic_types",
    label: "値型と参照型",
    language: "csharp",
    summary: "int や struct は値としてコピーされ、class は参照が渡る。どちらかで代入と引数渡しの意味が変わる。",
    prerequisites: ["csharp.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.control_flow",
    label: "if / for / switch",
    language: "csharp",
    summary: "条件分岐と繰り返し。foreach で列挙し、switch 式はパターンに応じた値を返せる。",
    prerequisites: ["csharp.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.class_basics",
    label: "class とプロパティ",
    language: "csharp",
    summary: "class でフィールドとメソッドを定義する。プロパティは get / set に手続きを挟める、フィールドに見える窓口である。",
    prerequisites: ["csharp.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.method_basics",
    label: "メソッドと引数",
    language: "csharp",
    summary: "戻り値の型と引数を宣言する。既定値と名前付き引数を取れ、ref / out で参照渡しや追加の戻り値を扱う。",
    prerequisites: ["csharp.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.inheritance",
    label: "継承と override",
    language: "csharp",
    summary: "基底クラスを継承し、virtual なメソッドを override で差し替える。base で基底の実装を呼ぶ。",
    prerequisites: ["csharp.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.interface_basics",
    label: "interface と実装",
    language: "csharp",
    summary: "実装を持たない約束を定義し、クラスや struct が満たす。依存を具体的な型から切り離すのに使う。",
    prerequisites: ["csharp.inheritance"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.collection_basics",
    label: "List / Dictionary",
    language: "csharp",
    summary: "可変長の List と、キーと値の Dictionary。無いキーの参照は例外になるため、TryGetValue で確認と取得を同時に行う。",
    prerequisites: ["csharp.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.linq",
    label: "LINQ とラムダ",
    language: "csharp",
    summary: "Where / Select / OrderBy でコレクションを問い合わせる。評価は遅延し、列挙した時点で初めて実行される。",
    prerequisites: ["csharp.collection_basics"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.async_await",
    label: "async / await と Task",
    language: "csharp",
    summary: "非同期処理を Task で表し、await で完了を待つ。async void は例外を捕まえられないため避ける。",
    prerequisites: ["csharp.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.error_handling",
    label: "throw / try / catch",
    language: "csharp",
    summary: "例外を投げて捕まえる。catch を型で分け、finally や using で後片付けを確実に行う。",
    prerequisites: ["csharp.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.dotnet_project",
    label: "csproj と dotnet CLI",
    language: "csharp",
    summary: "csproj に依存とターゲットを書き、dotnet build / run / test で操作する。",
    prerequisites: ["csharp.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "csharp.testing_basics",
    label: "xUnit の基本",
    language: "csharp",
    summary: "[Fact] や [Theory] を付けたメソッドを走らせ、Assert で期待値を確かめる。",
    prerequisites: ["csharp.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "php.variable_declaration",
    label: "$変数と代入",
    language: "php",
    summary: "変数は $ で始め、宣言せず代入で作る。関数の外にある変数は、中から自動では見えない。",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "php.basic_types",
    label: "スカラ型と null",
    language: "php",
    summary: "int / float / string / bool と null。== は型を変換して比べるため、意図しない一致を避けるには === を使う。",
    prerequisites: ["php.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "php.control_flow",
    label: "if / foreach / while",
    language: "php",
    summary: "条件分岐と繰り返し。foreach は配列のキーと値を順に受け取り、HTML へ埋め込む書き方もできる。",
    prerequisites: ["php.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "php.function_basics",
    label: "function と引数・戻り値",
    language: "php",
    summary: "function で定義し、引数と戻り値に型を宣言できる。既定値と可変長引数も取れる。",
    prerequisites: ["php.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "php.array_basics",
    label: "array と連想配列",
    language: "php",
    summary: "添字配列と連想配列が同じ array 型である。キーの有無は isset か array_key_exists で確かめる。",
    prerequisites: ["php.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "php.string_basics",
    label: "文字列操作とヒアドキュメント",
    language: "php",
    summary: "二重引用符の中では変数が展開され、単引用符では展開されない。連結は . で行い、長い文面はヒアドキュメントで書く。",
    prerequisites: ["php.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "php.class_basics",
    label: "class とインスタンス",
    language: "php",
    summary: "class でプロパティとメソッドを定義し、new で作る。自身は $this で参照し、メンバへは -> でアクセスする。",
    prerequisites: ["php.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "php.error_handling",
    label: "throw / try / catch",
    language: "php",
    summary: "例外を投げて捕まえる。Throwable を受けて記録し、握りつぶさずに呼び出し元へ伝える。",
    prerequisites: ["php.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "php.web_request",
    label: "$_GET / $_POST とレスポンス",
    language: "php",
    summary: "リクエストの値は $_GET や $_POST から読む。外部入力なので必ず検証し、出力するときにエスケープする。",
    prerequisites: ["php.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "php.composer",
    label: "Composer と autoload",
    language: "php",
    summary: "composer.json に依存を書き、vendor の autoload で読み込む。composer.lock でバージョンを固定する。",
    prerequisites: ["php.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "php.testing_basics",
    label: "PHPUnit の基本",
    language: "php",
    summary: "TestCase を継承したクラスに test メソッドを書き、assertSame などで期待値を確かめる。",
    prerequisites: ["php.function_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.variable_declaration",
    label: "変数と代入",
    language: "ruby",
    summary: "宣言せず代入で作る。先頭の記号でスコープが変わり、@ はインスタンス変数、大文字で始まる名前は定数になる。",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "ruby.basic_types",
    label: "数値・文字列・シンボルと nil",
    language: "ruby",
    summary: "Integer / Float / String と、名前を表す Symbol。値が無いことは nil で表し、nil と false だけが偽になる。",
    prerequisites: ["ruby.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.control_flow",
    label: "if / each / while",
    language: "ruby",
    summary: "条件分岐と繰り返し。if は値を返す式であり、繰り返しは while より each などのイテレータで書く。",
    prerequisites: ["ruby.variable_declaration"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.method_basics",
    label: "def と引数・戻り値",
    language: "ruby",
    summary: "def で定義する。最後に評価した式が戻り値になり、キーワード引数や既定値を取れる。",
    prerequisites: ["ruby.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.block_basics",
    label: "ブロックと each / map",
    language: "ruby",
    summary: "メソッドへ処理の塊を渡す仕組み。each は元の要素を順に渡し、map は変換した新しい配列を返す。",
    prerequisites: ["ruby.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.array_hash",
    label: "Array と Hash",
    language: "ruby",
    summary: "順序つきの Array と、キーと値の Hash。Hash のキーには文字列よりシンボルを使うのが一般的である。",
    prerequisites: ["ruby.basic_types"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.class_basics",
    label: "class とインスタンス変数",
    language: "ruby",
    summary: "class で定義し、initialize で初期化する。@ で始まる変数は外から直接触れず、attr_accessor などで公開する。",
    prerequisites: ["ruby.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.module_mixin",
    label: "module と mixin",
    language: "ruby",
    summary: "module に共通のふるまいをまとめ、include でクラスへ混ぜ込む。名前空間としても使う。",
    prerequisites: ["ruby.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.error_handling",
    label: "raise / rescue / ensure",
    language: "ruby",
    summary: "raise で例外を投げ、rescue で種類ごとに捕まえる。ensure は成功でも失敗でも必ず走る。",
    prerequisites: ["ruby.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.gem_bundler",
    label: "gem と Bundler",
    language: "ruby",
    summary: "Gemfile に依存を書き、bundle install で入れる。Gemfile.lock でバージョンを固定する。",
    prerequisites: ["ruby.class_basics"],
    source: { kind: "manual" },
  },
  {
    id: "ruby.testing_basics",
    label: "Minitest / RSpec の基本",
    language: "ruby",
    summary: "テストの単位を定義し、期待値との一致を検証する。前準備は setup や before にまとめる。",
    prerequisites: ["ruby.method_basics"],
    source: { kind: "manual" },
  },
  {
    id: "git.repository",
    label: "init / clone とリポジトリ",
    language: "git",
    summary: "git init で履歴の入れ物を作り、clone で既存のリポジトリを複製する。履歴は .git の中に全部ある。",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "git.staging",
    label: "add とステージング",
    language: "git",
    summary: "作業ツリーの変更のうち、次のコミットに含めるものを add で選ぶ。status と diff で選んだ内容を確かめる。",
    prerequisites: ["git.repository"],
    source: { kind: "manual" },
  },
  {
    id: "git.commit",
    label: "コミットとメッセージ",
    language: "git",
    summary: "ステージした内容を1つの変更として履歴へ記録する。メッセージには何を、なぜ変えたかを書く。",
    prerequisites: ["git.staging"],
    source: { kind: "manual" },
  },
  {
    id: "git.log_history",
    label: "log / diff で履歴を読む",
    language: "git",
    summary: "log で変更の並びを辿り、diff や show で中身を見る。いつ何が入ったかを調べる起点になる。",
    prerequisites: ["git.commit"],
    source: { kind: "manual" },
  },
  {
    id: "git.branch",
    label: "ブランチと切り替え",
    language: "git",
    summary: "履歴を分けて並行に作業する。switch で作業ツリーを別のブランチへ移し、未コミットの変更は持ち越される。",
    prerequisites: ["git.commit"],
    source: { kind: "manual" },
  },
  {
    id: "git.merge",
    label: "マージとコンフリクト解消",
    language: "git",
    summary: "分かれた履歴を1つに合わせる。同じ箇所が両方で変わっているとコンフリクトになり、手で解決してコミットする。",
    prerequisites: ["git.branch"],
    source: { kind: "manual" },
  },
  {
    id: "git.rebase",
    label: "rebase と履歴の書き換え",
    language: "git",
    summary: "コミットを別の土台へ付け替えて履歴を直線にする。共有済みのコミットを書き換えると、他の人の履歴とずれる。",
    prerequisites: ["git.merge"],
    source: { kind: "manual" },
  },
  {
    id: "git.remote",
    label: "remote / push / pull",
    language: "git",
    summary: "リモートリポジトリと履歴をやり取りする。push で送り、fetch や pull で取り込む。",
    prerequisites: ["git.commit"],
    source: { kind: "manual" },
  },
  {
    id: "git.stash",
    label: "stash と一時退避",
    language: "git",
    summary: "コミットしたくない変更を一時的に退避し、後で戻す。作業の途中で別の対応へ移るときに使う。",
    prerequisites: ["git.commit"],
    source: { kind: "manual" },
  },
  {
    id: "git.undo",
    label: "reset / revert による取り消し",
    language: "git",
    summary: "reset は履歴やステージを巻き戻し、revert は打ち消すコミットを新しく積む。共有済みなら revert を選ぶ。",
    prerequisites: ["git.commit"],
    source: { kind: "manual" },
  },
  {
    id: "design.naming",
    label: "命名と意図の表現",
    language: "design",
    summary: "名前で、それが何であり何のためにあるかを示す。読み手が実装を追わずに意図を掴めるかで良し悪しを判断する。",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "design.function_size",
    label: "関数の分割と責務",
    language: "design",
    summary: "1つの関数に1つの責務を持たせる。行数ではなく、やっていることを1文で言えるかで分割を決める。",
    prerequisites: ["design.naming"],
    source: { kind: "manual" },
  },
  {
    id: "design.dry",
    label: "重複と抽象化",
    language: "design",
    summary: "同じ知識の重複は減らす。ただし形が似ているだけのコードをまとめると、後から別々に変えられなくなる。",
    prerequisites: ["design.function_size"],
    source: { kind: "manual" },
  },
  {
    id: "design.dependency",
    label: "依存の方向と結合度",
    language: "design",
    summary: "どちらがどちらを知るかを決める。呼ばれる側が呼ぶ側を知らない形にすると、変更の影響が広がらない。",
    prerequisites: ["design.function_size"],
    source: { kind: "manual" },
  },
  {
    id: "design.interface_contract",
    label: "インターフェースと契約",
    language: "design",
    summary: "境界で交わす約束（引数・戻り値・失敗の表し方）を決める。実装の詳細を約束へ漏らさない。",
    prerequisites: ["design.dependency"],
    source: { kind: "manual" },
  },
  {
    id: "design.error_design",
    label: "エラーの表現と伝播",
    language: "design",
    summary: "失敗を戻り値と例外のどちらで表し、どこで扱うかを決める。握りつぶさず、呼び出し側が判断できる形で伝える。",
    prerequisites: ["design.function_size"],
    source: { kind: "manual" },
  },
  {
    id: "design.state",
    label: "状態と副作用の管理",
    language: "design",
    summary: "変わる状態をどこに置くかを決める。純粋な計算と副作用を分けると、動きを追いやすくなる。",
    prerequisites: ["design.function_size"],
    source: { kind: "manual" },
  },
  {
    id: "design.testability",
    label: "テストしやすい設計",
    language: "design",
    summary: "外部依存を境界へ追い出し、判断のロジックは引数と戻り値だけで書く。偽物が大量に要るのは設計が漏れている合図である。",
    prerequisites: ["design.dependency"],
    source: { kind: "manual" },
  },
  {
    id: "db.relational_model",
    label: "テーブルとリレーション",
    language: "db",
    summary: "データを行と列の表で表し、キーで表どうしを関係づける。1行が何を表すかを決めるのが出発点になる。",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "db.sql_select",
    label: "SELECT と WHERE",
    language: "db",
    summary: "必要な列と行を問い合わせる。条件で絞り、並び順と件数を指定して取り出す。",
    prerequisites: ["db.relational_model"],
    source: { kind: "manual" },
  },
  {
    id: "db.sql_join",
    label: "JOIN と結合",
    language: "db",
    summary: "複数の表をキーで繋いで1つの結果にする。内部結合と外部結合で、対応が無い行の扱いが変わる。",
    prerequisites: ["db.sql_select"],
    source: { kind: "manual" },
  },
  {
    id: "db.sql_aggregate",
    label: "GROUP BY と集約",
    language: "db",
    summary: "行をまとめて件数や合計を求める。集約の前に絞るか後に絞るかで、WHERE と HAVING のどちらを使うかが変わる。",
    prerequisites: ["db.sql_select"],
    source: { kind: "manual" },
  },
  {
    id: "db.sql_write",
    label: "INSERT / UPDATE / DELETE",
    language: "db",
    summary: "行の追加・更新・削除。UPDATE と DELETE は条件を書き忘れると全行に及ぶ。",
    prerequisites: ["db.relational_model"],
    source: { kind: "manual" },
  },
  {
    id: "db.normalization",
    label: "正規化と冗長性",
    language: "db",
    summary: "重複した事実を別の表へ分け、更新の食い違いを防ぐ。読み取りの都合で崩すときは理由を決めておく。",
    prerequisites: ["db.relational_model"],
    source: { kind: "manual" },
  },
  {
    id: "db.index",
    label: "インデックスと検索性能",
    language: "db",
    summary: "検索を速くする索引。書き込みは遅くなり容量も増えるため、実際に効く条件を見て張る。",
    prerequisites: ["db.sql_select"],
    source: { kind: "manual" },
  },
  {
    id: "db.transaction",
    label: "トランザクションと整合性",
    language: "db",
    summary: "複数の変更をまとめて、全部成功か全部取り消しにする。途中の状態を他から見せない。",
    prerequisites: ["db.sql_write"],
    source: { kind: "manual" },
  },
  {
    id: "db.migration",
    label: "スキーマ変更とマイグレーション",
    language: "db",
    summary: "スキーマの変更を順序つきの差分として記録し、どの環境でも同じ手順で同じ状態にする。",
    prerequisites: ["db.relational_model"],
    source: { kind: "manual" },
  },
  {
    id: "http.request_response",
    label: "リクエストとレスポンスの構造",
    language: "http",
    summary: "クライアントが要求を送り、サーバーが応答を返す。どちらも開始行・ヘッダ・本文で構成される。",
    prerequisites: [],
    source: { kind: "manual" },
  },
  {
    id: "http.method_semantics",
    label: "GET / POST などメソッドの意味",
    language: "http",
    summary: "操作の種類をメソッドで表す。GET は取得で状態を変えず、状態を変える要求には POST などを使う。",
    prerequisites: ["http.request_response"],
    source: { kind: "manual" },
  },
  {
    id: "http.status_code",
    label: "ステータスコードの区分",
    language: "http",
    summary: "2xx は成功、3xx は転送、4xx は要求側の誤り、5xx はサーバー側の失敗。区分を守ると呼び出し側が機械的に判断できる。",
    prerequisites: ["http.request_response"],
    source: { kind: "manual" },
  },
  {
    id: "http.header",
    label: "ヘッダと Content-Type",
    language: "http",
    summary: "本文の形式やキャッシュの指示をヘッダで伝える。Content-Type が実際の本文と違うと、受け取り側の解釈がずれる。",
    prerequisites: ["http.request_response"],
    source: { kind: "manual" },
  },
  {
    id: "http.rest",
    label: "REST のリソース指向",
    language: "http",
    summary: "URL でリソースを指し、操作はメソッドで表す。URL へ動詞を入れず、状態の変化を統一した形で扱う。",
    prerequisites: ["http.method_semantics"],
    source: { kind: "manual" },
  },
  {
    id: "http.cors",
    label: "CORS とオリジン",
    language: "http",
    summary: "ブラウザは別オリジンへの要求を既定で制限する。サーバーが許可を応答ヘッダで示し、資格情報つきの要求では許可を無制限にしない。",
    prerequisites: ["http.header"],
    source: { kind: "manual" },
  },
  {
    id: "http.auth",
    label: "認証ヘッダとトークン",
    language: "http",
    summary: "Authorization ヘッダでトークンを渡す。転送先が変わると資格情報が漏れるため、送る相手を限定する。",
    prerequisites: ["http.header"],
    source: { kind: "manual" },
  },
];

/** Concept ID から定義を引く。未知の ID では undefined を返す。 */
export const CONCEPT_BY_ID: ReadonlyMap<ConceptId, Concept> = new Map(
  CONCEPTS.map((concept) => [concept.id, concept]),
);
