/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings src/worker/worker-configuration.d.ts` (hash: f76f82a95bd513f584ff04018a24155f)
interface __BaseEnv_CloudflareBindings {
  SESSIONS: KVNamespace;
  LOGIN_RATE_LIMITER: RateLimit;
  ASSETS: Fetcher;
  API_ORIGIN: string;
  AUTH_ISSUER: string;
  AUTH_AUDIENCE: string;
  AUTH_CLIENT_ID: string;
  AUTH_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      "API_ORIGIN" | "AUTH_ISSUER" | "AUTH_AUDIENCE" | "AUTH_CLIENT_ID" | "AUTH_CLIENT_SECRET"
    >
  > {}
}
