/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings src/worker-configuration.d.ts` (hash: bdec80f445ac59119b4de8129011e8cc)
interface __BaseEnv_CloudflareBindings {
  DB: D1Database;
  SYNC_RATE_LIMITER: RateLimit;
  PROFILE_RATE_LIMITER: RateLimit;
  MASTERY_OVERRIDE_RATE_LIMITER: RateLimit;
  MAP_RATE_LIMITER: RateLimit;
  CORS_ALLOWED_ORIGINS: string;
  GEMINI_MODEL: string;
  CHECK_MODELS: string;
  REPO_MAP_SUMMARY_MODELS: string;
  CHECK_GENERATION_LIMITS: string;
  AUTH_ISSUER: string;
  AUTH_AUDIENCE: string;
  GEMINI_API_KEY: string;
  GITHUB_TOKEN: string;
  AUTH_MANAGEMENT_CLIENT_ID: string;
  AUTH_MANAGEMENT_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "CORS_ALLOWED_ORIGINS"
      | "GEMINI_MODEL"
      | "CHECK_MODELS"
      | "REPO_MAP_SUMMARY_MODELS"
      | "CHECK_GENERATION_LIMITS"
      | "AUTH_ISSUER"
      | "AUTH_AUDIENCE"
      | "GEMINI_API_KEY"
      | "GITHUB_TOKEN"
      | "AUTH_MANAGEMENT_CLIENT_ID"
      | "AUTH_MANAGEMENT_CLIENT_SECRET"
    >
  > {}
}
