/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FramedRouteRouteImport } from './routes/_framed/route'
import { Route as LoginFailedRouteImport } from './routes/login-failed'
import { Route as FramedIndexRouteImport } from './routes/_framed/index'
import { Route as FramedActivityRouteImport } from './routes/_framed/activity'
import { Route as FramedSettingsRouteImport } from './routes/_framed/settings'

const FramedRouteRoute = FramedRouteRouteImport.update({
  id: '/_framed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginFailedRoute = LoginFailedRouteImport.update({
  id: '/login-failed',
  path: '/login-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const FramedIndexRoute = FramedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedActivityRoute = FramedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedSettingsRoute = FramedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FramedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof FramedIndexRoute
  '/login-failed': typeof LoginFailedRoute
  '/activity': typeof FramedActivityRoute
  '/settings': typeof FramedSettingsRoute
}
export interface FileRoutesByTo {
  '/login-failed': typeof LoginFailedRoute
  '/activity': typeof FramedActivityRoute
  '/settings': typeof FramedSettingsRoute
  '/': typeof FramedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_framed': typeof FramedRouteRouteWithChildren
  '/login-failed': typeof LoginFailedRoute
  '/_framed/activity': typeof FramedActivityRoute
  '/_framed/settings': typeof FramedSettingsRoute
  '/_framed/': typeof FramedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login-failed' | '/activity' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/login-failed' | '/activity' | '/settings' | '/'
  id:
    | '__root__'
    | '/_framed'
    | '/login-failed'
    | '/_framed/activity'
    | '/_framed/settings'
    | '/_framed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FramedRouteRoute: typeof FramedRouteRouteWithChildren
  LoginFailedRoute: typeof LoginFailedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_framed': {
      id: '/_framed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FramedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-failed': {
      id: '/login-failed'
      path: '/login-failed'
      fullPath: '/login-failed'
      preLoaderRoute: typeof LoginFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_framed/': {
      id: '/_framed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FramedIndexRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/activity': {
      id: '/_framed/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof FramedActivityRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/settings': {
      id: '/_framed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof FramedSettingsRouteImport
      parentRoute: typeof FramedRouteRoute
    }
  }
}

interface FramedRouteRouteChildren {
  FramedActivityRoute: typeof FramedActivityRoute
  FramedSettingsRoute: typeof FramedSettingsRoute
  FramedIndexRoute: typeof FramedIndexRoute
}

const FramedRouteRouteChildren: FramedRouteRouteChildren = {
  FramedActivityRoute: FramedActivityRoute,
  FramedSettingsRoute: FramedSettingsRoute,
  FramedIndexRoute: FramedIndexRoute,
}

const FramedRouteRouteWithChildren = FramedRouteRoute._addFileChildren(
  FramedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  FramedRouteRoute: FramedRouteRouteWithChildren,
  LoginFailedRoute: LoginFailedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
