/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FramedRouteRouteImport } from './routes/_framed/route'
import { Route as LoginFailedRouteImport } from './routes/login-failed'
import { Route as FramedIndexRouteImport } from './routes/_framed/index'
import { Route as FramedActivityRouteImport } from './routes/_framed/activity'
import { Route as FramedSettingsRouteRouteImport } from './routes/_framed/settings/route'
import { Route as FramedSettingsIndexRouteImport } from './routes/_framed/settings/index'
import { Route as FramedSettingsBillingRouteImport } from './routes/_framed/settings/billing'
import { Route as FramedSettingsUsageRouteImport } from './routes/_framed/settings/usage'

const FramedRouteRoute = FramedRouteRouteImport.update({
  id: '/_framed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginFailedRoute = LoginFailedRouteImport.update({
  id: '/login-failed',
  path: '/login-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const FramedIndexRoute = FramedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedActivityRoute = FramedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedSettingsRouteRoute = FramedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedSettingsIndexRoute = FramedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FramedSettingsRouteRoute,
} as any)
const FramedSettingsBillingRoute = FramedSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => FramedSettingsRouteRoute,
} as any)
const FramedSettingsUsageRoute = FramedSettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => FramedSettingsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof FramedIndexRoute
  '/login-failed': typeof LoginFailedRoute
  '/settings': typeof FramedSettingsRouteRouteWithChildren
  '/activity': typeof FramedActivityRoute
  '/settings/billing': typeof FramedSettingsBillingRoute
  '/settings/usage': typeof FramedSettingsUsageRoute
  '/settings/': typeof FramedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login-failed': typeof LoginFailedRoute
  '/activity': typeof FramedActivityRoute
  '/': typeof FramedIndexRoute
  '/settings/billing': typeof FramedSettingsBillingRoute
  '/settings/usage': typeof FramedSettingsUsageRoute
  '/settings': typeof FramedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_framed': typeof FramedRouteRouteWithChildren
  '/login-failed': typeof LoginFailedRoute
  '/_framed/settings': typeof FramedSettingsRouteRouteWithChildren
  '/_framed/activity': typeof FramedActivityRoute
  '/_framed/': typeof FramedIndexRoute
  '/_framed/settings/billing': typeof FramedSettingsBillingRoute
  '/_framed/settings/usage': typeof FramedSettingsUsageRoute
  '/_framed/settings/': typeof FramedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login-failed'
    | '/settings'
    | '/activity'
    | '/settings/billing'
    | '/settings/usage'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login-failed'
    | '/activity'
    | '/'
    | '/settings/billing'
    | '/settings/usage'
    | '/settings'
  id:
    | '__root__'
    | '/_framed'
    | '/login-failed'
    | '/_framed/settings'
    | '/_framed/activity'
    | '/_framed/'
    | '/_framed/settings/billing'
    | '/_framed/settings/usage'
    | '/_framed/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FramedRouteRoute: typeof FramedRouteRouteWithChildren
  LoginFailedRoute: typeof LoginFailedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_framed': {
      id: '/_framed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FramedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-failed': {
      id: '/login-failed'
      path: '/login-failed'
      fullPath: '/login-failed'
      preLoaderRoute: typeof LoginFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_framed/': {
      id: '/_framed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FramedIndexRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/activity': {
      id: '/_framed/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof FramedActivityRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/settings': {
      id: '/_framed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof FramedSettingsRouteRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/settings/': {
      id: '/_framed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof FramedSettingsIndexRouteImport
      parentRoute: typeof FramedSettingsRouteRoute
    }
    '/_framed/settings/billing': {
      id: '/_framed/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof FramedSettingsBillingRouteImport
      parentRoute: typeof FramedSettingsRouteRoute
    }
    '/_framed/settings/usage': {
      id: '/_framed/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof FramedSettingsUsageRouteImport
      parentRoute: typeof FramedSettingsRouteRoute
    }
  }
}

interface FramedSettingsRouteRouteChildren {
  FramedSettingsBillingRoute: typeof FramedSettingsBillingRoute
  FramedSettingsUsageRoute: typeof FramedSettingsUsageRoute
  FramedSettingsIndexRoute: typeof FramedSettingsIndexRoute
}

const FramedSettingsRouteRouteChildren: FramedSettingsRouteRouteChildren = {
  FramedSettingsBillingRoute: FramedSettingsBillingRoute,
  FramedSettingsUsageRoute: FramedSettingsUsageRoute,
  FramedSettingsIndexRoute: FramedSettingsIndexRoute,
}

const FramedSettingsRouteRouteWithChildren =
  FramedSettingsRouteRoute._addFileChildren(FramedSettingsRouteRouteChildren)

interface FramedRouteRouteChildren {
  FramedSettingsRouteRoute: typeof FramedSettingsRouteRouteWithChildren
  FramedActivityRoute: typeof FramedActivityRoute
  FramedIndexRoute: typeof FramedIndexRoute
}

const FramedRouteRouteChildren: FramedRouteRouteChildren = {
  FramedSettingsRouteRoute: FramedSettingsRouteRouteWithChildren,
  FramedActivityRoute: FramedActivityRoute,
  FramedIndexRoute: FramedIndexRoute,
}

const FramedRouteRouteWithChildren = FramedRouteRoute._addFileChildren(
  FramedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  FramedRouteRoute: FramedRouteRouteWithChildren,
  LoginFailedRoute: LoginFailedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
