/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FramedRouteRouteImport } from './routes/_framed/route'
import { Route as LoginFailedRouteImport } from './routes/login-failed'
import { Route as FramedIndexRouteImport } from './routes/_framed/index'
import { Route as FramedActivityRouteImport } from './routes/_framed/activity'
import { Route as FramedSettingsRouteRouteImport } from './routes/_framed/settings/route'
import { Route as FramedCheckConceptIdRouteImport } from './routes/_framed/check.$conceptId'
import { Route as FramedHistoryIndexRouteImport } from './routes/_framed/history.index'
import { Route as FramedHistoryConversationIdRouteImport } from './routes/_framed/history.$conversationId'
import { Route as FramedMapLanguageRouteImport } from './routes/_framed/map.$language'
import { Route as FramedMapsIndexRouteImport } from './routes/_framed/maps.index'
import { Route as FramedMapsMapIdRouteImport } from './routes/_framed/maps.$mapId'
import { Route as FramedMapsGenerateRouteImport } from './routes/_framed/maps.generate'
import { Route as FramedSettingsIndexRouteImport } from './routes/_framed/settings/index'
import { Route as FramedSettingsBillingRouteImport } from './routes/_framed/settings/billing'
import { Route as FramedSettingsDataRouteImport } from './routes/_framed/settings/data'
import { Route as FramedSettingsUsageRouteImport } from './routes/_framed/settings/usage'
import { Route as FramedSharedIndexRouteImport } from './routes/_framed/shared.index'
import { Route as FramedSharedMapIdRouteImport } from './routes/_framed/shared.$mapId'
import { Route as FramedMapLanguageObjectivesRouteImport } from './routes/_framed/map.$language_.objectives'
import { Route as FramedMapsMapIdEditRouteImport } from './routes/_framed/maps.$mapId_.edit'
import { Route as FramedMapsMapIdHistoryRouteImport } from './routes/_framed/maps.$mapId_.history'
import { Route as FramedMapsMapIdReimportRouteImport } from './routes/_framed/maps.$mapId_.reimport'
import { Route as FramedMapsMapIdShareRouteImport } from './routes/_framed/maps.$mapId_.share'

const FramedRouteRoute = FramedRouteRouteImport.update({
  id: '/_framed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginFailedRoute = LoginFailedRouteImport.update({
  id: '/login-failed',
  path: '/login-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const FramedIndexRoute = FramedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedActivityRoute = FramedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedSettingsRouteRoute = FramedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedCheckConceptIdRoute = FramedCheckConceptIdRouteImport.update({
  id: '/check/$conceptId',
  path: '/check/$conceptId',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedHistoryIndexRoute = FramedHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedHistoryConversationIdRoute =
  FramedHistoryConversationIdRouteImport.update({
    id: '/history/$conversationId',
    path: '/history/$conversationId',
    getParentRoute: () => FramedRouteRoute,
  } as any)
const FramedMapLanguageRoute = FramedMapLanguageRouteImport.update({
  id: '/map/$language',
  path: '/map/$language',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedMapsIndexRoute = FramedMapsIndexRouteImport.update({
  id: '/maps/',
  path: '/maps/',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedMapsMapIdRoute = FramedMapsMapIdRouteImport.update({
  id: '/maps/$mapId',
  path: '/maps/$mapId',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedMapsGenerateRoute = FramedMapsGenerateRouteImport.update({
  id: '/maps/generate',
  path: '/maps/generate',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedSettingsIndexRoute = FramedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FramedSettingsRouteRoute,
} as any)
const FramedSettingsBillingRoute = FramedSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => FramedSettingsRouteRoute,
} as any)
const FramedSettingsDataRoute = FramedSettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => FramedSettingsRouteRoute,
} as any)
const FramedSettingsUsageRoute = FramedSettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => FramedSettingsRouteRoute,
} as any)
const FramedSharedIndexRoute = FramedSharedIndexRouteImport.update({
  id: '/shared/',
  path: '/shared/',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedSharedMapIdRoute = FramedSharedMapIdRouteImport.update({
  id: '/shared/$mapId',
  path: '/shared/$mapId',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedMapLanguageObjectivesRoute =
  FramedMapLanguageObjectivesRouteImport.update({
    id: '/map/$language_/objectives',
    path: '/map/$language/objectives',
    getParentRoute: () => FramedRouteRoute,
  } as any)
const FramedMapsMapIdEditRoute = FramedMapsMapIdEditRouteImport.update({
  id: '/maps/$mapId_/edit',
  path: '/maps/$mapId/edit',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedMapsMapIdHistoryRoute = FramedMapsMapIdHistoryRouteImport.update({
  id: '/maps/$mapId_/history',
  path: '/maps/$mapId/history',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedMapsMapIdReimportRoute = FramedMapsMapIdReimportRouteImport.update({
  id: '/maps/$mapId_/reimport',
  path: '/maps/$mapId/reimport',
  getParentRoute: () => FramedRouteRoute,
} as any)
const FramedMapsMapIdShareRoute = FramedMapsMapIdShareRouteImport.update({
  id: '/maps/$mapId_/share',
  path: '/maps/$mapId/share',
  getParentRoute: () => FramedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof FramedIndexRoute
  '/login-failed': typeof LoginFailedRoute
  '/settings': typeof FramedSettingsRouteRouteWithChildren
  '/activity': typeof FramedActivityRoute
  '/check/$conceptId': typeof FramedCheckConceptIdRoute
  '/history/$conversationId': typeof FramedHistoryConversationIdRoute
  '/map/$language': typeof FramedMapLanguageRoute
  '/maps/$mapId': typeof FramedMapsMapIdRoute
  '/maps/generate': typeof FramedMapsGenerateRoute
  '/settings/billing': typeof FramedSettingsBillingRoute
  '/settings/data': typeof FramedSettingsDataRoute
  '/settings/usage': typeof FramedSettingsUsageRoute
  '/shared/$mapId': typeof FramedSharedMapIdRoute
  '/history/': typeof FramedHistoryIndexRoute
  '/maps/': typeof FramedMapsIndexRoute
  '/settings/': typeof FramedSettingsIndexRoute
  '/shared/': typeof FramedSharedIndexRoute
  '/map/$language/objectives': typeof FramedMapLanguageObjectivesRoute
  '/maps/$mapId/edit': typeof FramedMapsMapIdEditRoute
  '/maps/$mapId/history': typeof FramedMapsMapIdHistoryRoute
  '/maps/$mapId/reimport': typeof FramedMapsMapIdReimportRoute
  '/maps/$mapId/share': typeof FramedMapsMapIdShareRoute
}
export interface FileRoutesByTo {
  '/login-failed': typeof LoginFailedRoute
  '/activity': typeof FramedActivityRoute
  '/': typeof FramedIndexRoute
  '/check/$conceptId': typeof FramedCheckConceptIdRoute
  '/history/$conversationId': typeof FramedHistoryConversationIdRoute
  '/map/$language': typeof FramedMapLanguageRoute
  '/maps/$mapId': typeof FramedMapsMapIdRoute
  '/maps/generate': typeof FramedMapsGenerateRoute
  '/settings/billing': typeof FramedSettingsBillingRoute
  '/settings/data': typeof FramedSettingsDataRoute
  '/settings/usage': typeof FramedSettingsUsageRoute
  '/shared/$mapId': typeof FramedSharedMapIdRoute
  '/history': typeof FramedHistoryIndexRoute
  '/maps': typeof FramedMapsIndexRoute
  '/settings': typeof FramedSettingsIndexRoute
  '/shared': typeof FramedSharedIndexRoute
  '/map/$language/objectives': typeof FramedMapLanguageObjectivesRoute
  '/maps/$mapId/edit': typeof FramedMapsMapIdEditRoute
  '/maps/$mapId/history': typeof FramedMapsMapIdHistoryRoute
  '/maps/$mapId/reimport': typeof FramedMapsMapIdReimportRoute
  '/maps/$mapId/share': typeof FramedMapsMapIdShareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_framed': typeof FramedRouteRouteWithChildren
  '/login-failed': typeof LoginFailedRoute
  '/_framed/settings': typeof FramedSettingsRouteRouteWithChildren
  '/_framed/activity': typeof FramedActivityRoute
  '/_framed/': typeof FramedIndexRoute
  '/_framed/check/$conceptId': typeof FramedCheckConceptIdRoute
  '/_framed/history/$conversationId': typeof FramedHistoryConversationIdRoute
  '/_framed/map/$language': typeof FramedMapLanguageRoute
  '/_framed/maps/$mapId': typeof FramedMapsMapIdRoute
  '/_framed/maps/generate': typeof FramedMapsGenerateRoute
  '/_framed/settings/billing': typeof FramedSettingsBillingRoute
  '/_framed/settings/data': typeof FramedSettingsDataRoute
  '/_framed/settings/usage': typeof FramedSettingsUsageRoute
  '/_framed/shared/$mapId': typeof FramedSharedMapIdRoute
  '/_framed/history/': typeof FramedHistoryIndexRoute
  '/_framed/maps/': typeof FramedMapsIndexRoute
  '/_framed/settings/': typeof FramedSettingsIndexRoute
  '/_framed/shared/': typeof FramedSharedIndexRoute
  '/_framed/map/$language_/objectives': typeof FramedMapLanguageObjectivesRoute
  '/_framed/maps/$mapId_/edit': typeof FramedMapsMapIdEditRoute
  '/_framed/maps/$mapId_/history': typeof FramedMapsMapIdHistoryRoute
  '/_framed/maps/$mapId_/reimport': typeof FramedMapsMapIdReimportRoute
  '/_framed/maps/$mapId_/share': typeof FramedMapsMapIdShareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login-failed'
    | '/settings'
    | '/activity'
    | '/check/$conceptId'
    | '/history/$conversationId'
    | '/map/$language'
    | '/maps/$mapId'
    | '/maps/generate'
    | '/settings/billing'
    | '/settings/data'
    | '/settings/usage'
    | '/shared/$mapId'
    | '/history/'
    | '/maps/'
    | '/settings/'
    | '/shared/'
    | '/map/$language/objectives'
    | '/maps/$mapId/edit'
    | '/maps/$mapId/history'
    | '/maps/$mapId/reimport'
    | '/maps/$mapId/share'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login-failed'
    | '/activity'
    | '/'
    | '/check/$conceptId'
    | '/history/$conversationId'
    | '/map/$language'
    | '/maps/$mapId'
    | '/maps/generate'
    | '/settings/billing'
    | '/settings/data'
    | '/settings/usage'
    | '/shared/$mapId'
    | '/history'
    | '/maps'
    | '/settings'
    | '/shared'
    | '/map/$language/objectives'
    | '/maps/$mapId/edit'
    | '/maps/$mapId/history'
    | '/maps/$mapId/reimport'
    | '/maps/$mapId/share'
  id:
    | '__root__'
    | '/_framed'
    | '/login-failed'
    | '/_framed/settings'
    | '/_framed/activity'
    | '/_framed/'
    | '/_framed/check/$conceptId'
    | '/_framed/history/$conversationId'
    | '/_framed/map/$language'
    | '/_framed/maps/$mapId'
    | '/_framed/maps/generate'
    | '/_framed/settings/billing'
    | '/_framed/settings/data'
    | '/_framed/settings/usage'
    | '/_framed/shared/$mapId'
    | '/_framed/history/'
    | '/_framed/maps/'
    | '/_framed/settings/'
    | '/_framed/shared/'
    | '/_framed/map/$language_/objectives'
    | '/_framed/maps/$mapId_/edit'
    | '/_framed/maps/$mapId_/history'
    | '/_framed/maps/$mapId_/reimport'
    | '/_framed/maps/$mapId_/share'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FramedRouteRoute: typeof FramedRouteRouteWithChildren
  LoginFailedRoute: typeof LoginFailedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_framed': {
      id: '/_framed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FramedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-failed': {
      id: '/login-failed'
      path: '/login-failed'
      fullPath: '/login-failed'
      preLoaderRoute: typeof LoginFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_framed/': {
      id: '/_framed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FramedIndexRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/activity': {
      id: '/_framed/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof FramedActivityRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/settings': {
      id: '/_framed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof FramedSettingsRouteRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/check/$conceptId': {
      id: '/_framed/check/$conceptId'
      path: '/check/$conceptId'
      fullPath: '/check/$conceptId'
      preLoaderRoute: typeof FramedCheckConceptIdRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/history/': {
      id: '/_framed/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof FramedHistoryIndexRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/history/$conversationId': {
      id: '/_framed/history/$conversationId'
      path: '/history/$conversationId'
      fullPath: '/history/$conversationId'
      preLoaderRoute: typeof FramedHistoryConversationIdRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/map/$language': {
      id: '/_framed/map/$language'
      path: '/map/$language'
      fullPath: '/map/$language'
      preLoaderRoute: typeof FramedMapLanguageRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/maps/': {
      id: '/_framed/maps/'
      path: '/maps'
      fullPath: '/maps/'
      preLoaderRoute: typeof FramedMapsIndexRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/maps/$mapId': {
      id: '/_framed/maps/$mapId'
      path: '/maps/$mapId'
      fullPath: '/maps/$mapId'
      preLoaderRoute: typeof FramedMapsMapIdRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/maps/generate': {
      id: '/_framed/maps/generate'
      path: '/maps/generate'
      fullPath: '/maps/generate'
      preLoaderRoute: typeof FramedMapsGenerateRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/settings/': {
      id: '/_framed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof FramedSettingsIndexRouteImport
      parentRoute: typeof FramedSettingsRouteRoute
    }
    '/_framed/settings/billing': {
      id: '/_framed/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof FramedSettingsBillingRouteImport
      parentRoute: typeof FramedSettingsRouteRoute
    }
    '/_framed/settings/data': {
      id: '/_framed/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof FramedSettingsDataRouteImport
      parentRoute: typeof FramedSettingsRouteRoute
    }
    '/_framed/settings/usage': {
      id: '/_framed/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof FramedSettingsUsageRouteImport
      parentRoute: typeof FramedSettingsRouteRoute
    }
    '/_framed/shared/': {
      id: '/_framed/shared/'
      path: '/shared'
      fullPath: '/shared/'
      preLoaderRoute: typeof FramedSharedIndexRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/shared/$mapId': {
      id: '/_framed/shared/$mapId'
      path: '/shared/$mapId'
      fullPath: '/shared/$mapId'
      preLoaderRoute: typeof FramedSharedMapIdRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/map/$language_/objectives': {
      id: '/_framed/map/$language_/objectives'
      path: '/map/$language/objectives'
      fullPath: '/map/$language/objectives'
      preLoaderRoute: typeof FramedMapLanguageObjectivesRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/maps/$mapId_/edit': {
      id: '/_framed/maps/$mapId_/edit'
      path: '/maps/$mapId/edit'
      fullPath: '/maps/$mapId/edit'
      preLoaderRoute: typeof FramedMapsMapIdEditRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/maps/$mapId_/history': {
      id: '/_framed/maps/$mapId_/history'
      path: '/maps/$mapId/history'
      fullPath: '/maps/$mapId/history'
      preLoaderRoute: typeof FramedMapsMapIdHistoryRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/maps/$mapId_/reimport': {
      id: '/_framed/maps/$mapId_/reimport'
      path: '/maps/$mapId/reimport'
      fullPath: '/maps/$mapId/reimport'
      preLoaderRoute: typeof FramedMapsMapIdReimportRouteImport
      parentRoute: typeof FramedRouteRoute
    }
    '/_framed/maps/$mapId_/share': {
      id: '/_framed/maps/$mapId_/share'
      path: '/maps/$mapId/share'
      fullPath: '/maps/$mapId/share'
      preLoaderRoute: typeof FramedMapsMapIdShareRouteImport
      parentRoute: typeof FramedRouteRoute
    }
  }
}

interface FramedSettingsRouteRouteChildren {
  FramedSettingsBillingRoute: typeof FramedSettingsBillingRoute
  FramedSettingsDataRoute: typeof FramedSettingsDataRoute
  FramedSettingsUsageRoute: typeof FramedSettingsUsageRoute
  FramedSettingsIndexRoute: typeof FramedSettingsIndexRoute
}

const FramedSettingsRouteRouteChildren: FramedSettingsRouteRouteChildren = {
  FramedSettingsBillingRoute: FramedSettingsBillingRoute,
  FramedSettingsDataRoute: FramedSettingsDataRoute,
  FramedSettingsUsageRoute: FramedSettingsUsageRoute,
  FramedSettingsIndexRoute: FramedSettingsIndexRoute,
}

const FramedSettingsRouteRouteWithChildren =
  FramedSettingsRouteRoute._addFileChildren(FramedSettingsRouteRouteChildren)

interface FramedRouteRouteChildren {
  FramedSettingsRouteRoute: typeof FramedSettingsRouteRouteWithChildren
  FramedActivityRoute: typeof FramedActivityRoute
  FramedIndexRoute: typeof FramedIndexRoute
  FramedCheckConceptIdRoute: typeof FramedCheckConceptIdRoute
  FramedHistoryConversationIdRoute: typeof FramedHistoryConversationIdRoute
  FramedMapLanguageRoute: typeof FramedMapLanguageRoute
  FramedMapsMapIdRoute: typeof FramedMapsMapIdRoute
  FramedMapsGenerateRoute: typeof FramedMapsGenerateRoute
  FramedSharedMapIdRoute: typeof FramedSharedMapIdRoute
  FramedHistoryIndexRoute: typeof FramedHistoryIndexRoute
  FramedMapsIndexRoute: typeof FramedMapsIndexRoute
  FramedSharedIndexRoute: typeof FramedSharedIndexRoute
  FramedMapLanguageObjectivesRoute: typeof FramedMapLanguageObjectivesRoute
  FramedMapsMapIdEditRoute: typeof FramedMapsMapIdEditRoute
  FramedMapsMapIdHistoryRoute: typeof FramedMapsMapIdHistoryRoute
  FramedMapsMapIdReimportRoute: typeof FramedMapsMapIdReimportRoute
  FramedMapsMapIdShareRoute: typeof FramedMapsMapIdShareRoute
}

const FramedRouteRouteChildren: FramedRouteRouteChildren = {
  FramedSettingsRouteRoute: FramedSettingsRouteRouteWithChildren,
  FramedActivityRoute: FramedActivityRoute,
  FramedIndexRoute: FramedIndexRoute,
  FramedCheckConceptIdRoute: FramedCheckConceptIdRoute,
  FramedHistoryConversationIdRoute: FramedHistoryConversationIdRoute,
  FramedMapLanguageRoute: FramedMapLanguageRoute,
  FramedMapsMapIdRoute: FramedMapsMapIdRoute,
  FramedMapsGenerateRoute: FramedMapsGenerateRoute,
  FramedSharedMapIdRoute: FramedSharedMapIdRoute,
  FramedHistoryIndexRoute: FramedHistoryIndexRoute,
  FramedMapsIndexRoute: FramedMapsIndexRoute,
  FramedSharedIndexRoute: FramedSharedIndexRoute,
  FramedMapLanguageObjectivesRoute: FramedMapLanguageObjectivesRoute,
  FramedMapsMapIdEditRoute: FramedMapsMapIdEditRoute,
  FramedMapsMapIdHistoryRoute: FramedMapsMapIdHistoryRoute,
  FramedMapsMapIdReimportRoute: FramedMapsMapIdReimportRoute,
  FramedMapsMapIdShareRoute: FramedMapsMapIdShareRoute,
}

const FramedRouteRouteWithChildren = FramedRouteRoute._addFileChildren(
  FramedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  FramedRouteRoute: FramedRouteRouteWithChildren,
  LoginFailedRoute: LoginFailedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
